config/routes.rb
Rails.application.routes.draw do
  # ActiveAdmin routing
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get 'welcome/index'

  resources :categories, only: [:index, :show] do
    resources :articles, only: [:index, :show]
  end

  resources :articles, only: :show

  root 'welcome#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :category
  validates :title, :body, presence: true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :articles, dependent: :destroy
  validates :title, presence: true

  def to_param
    [id, title.parameterize].join("-")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @category = Category.find(params[:category_id])
    @articles = @category.articles.all
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
var disqus_config = function () {
  this.shortname = "jackore";
  this.page.url = "<%= url_for(host: ENV['APPLICATION_HOST']) %>";
  this.page.identifier = 'article-<%= @article.id %>';
  this.page.title = '<%= @article.title %>';  
};
(function() {
var d = document, s = d.createElement('script');
s.src = '//nimblefact.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="2"></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.body %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.body %>
</p>

<%= render 'disqus' %>

<%= link_to 'Back', category_path(@article.category) %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Title</th>
    <th colspan="2"></th>
  </tr>
  <% @categories.each do |category| %>
    <tr>
      <td><%= link_to "#{category.title}", category_path(category) %></td>
    </tr>
  <% end %>
</table>

app/views/categories/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="1"></th>
  </tr>
    <% @category.articles.each do |article| %>
      <tr>
        <td><%= link_to article.title.to_s, category_article_path(article) %></td>
        <td><%= article.body[0..20] %></td>
      <tr>
    <% end %>
  <tr></tr>
</table>

<%= link_to 'Back to categories', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Personal blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <div class="content">
    <body>
      <%= yield %>
    </body>
  </div>
</html>

app/views/welcome/index.html.erb
<h1>Kickthrough blog</h1>
<p><%= link_to "Categories", categories_path %></p>